language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: COMPILER=clang++-5.0
    #- os: osx
      #compiler: clang
      #osx_image: xcode6.4
    #- os: osx
      #compiler: clang
      #osx_image: xcode7.3

#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y sfml

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-add-repository ppa:beineri/opt-qt521-trusty -y
      sudo apt-get update -qq
      sudo apt-get install mesa-common-dev qt52base qt52connectivity -y
      export PRE_PATH=/opt/qt52
      CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh"
      CMAKE_INSTALLER="cmake-3.6.3-Linux-x86_64.sh"
      wget --no-check-certificate --quiet -O ${CMAKE_INSTALLER} - ${CMAKE_URL}
      sh ${CMAKE_INSTALLER} --prefix=$HOME --exclude-subdir
    else
      brew update
      brew uninstall --force cmake
      brew install cmake
      brew install qt5
      export PRE_PATH=$(brew --prefix qt5)
    fi

script:
  - |
    cd ${TRAVIS_BUILD_DIR} && pwd
    mkdir build
    cd build && pwd
    cmake -DBUILD_QACCORDION_DEMO=ON -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_PREFIX_PATH=${PRE_PATH} ../ && make

# blacklist
branches:
  except:
    #    - develop
    - gh-pages

#notifications:
#  webhooks:
#    urls: https://webhooks.gitter.im/e/
#    on_success: change
#
